### ISSUE TITLE
Abbreviations test comments need updating?

### ISSUE THREAD

**Issue by knod** [FinNLP/lexed#2]
Or something does. The test seems to be testing "ADA" not "M." or "Mme.": https://github.com/FinNLP/lexed/blob/master/test/extending.abbreviations.ts#L10-L14. It's unclear why "m" is included in the abbreviations list, though.

I haven't tried this out myself yet, but is it correct that the initial result would have been `["M. et Mme.","Pierre Dubois sont allés à la tribune hier soir."]`? Would "M." not be a sentence by itself without the abbreviations list?

Less of a contradiction is https://github.com/FinNLP/lexed/blob/master/test/extending.abbreviations.ts#L4, which says, "which means Monsieur. and Madame. respectively in French." and should say, "which means Monsieur and Madame respectively in French." without the periods.

**Comment by alexcorvi** [comment]
Sorry for the delay, it's fixed now. It was a weird bug that I had then I realized that built-in english extension test is polluting other test such as the examples.
